---
- hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: Debug
      debug: var=inventory_hostname

    - name: selenium
      selenium_test:
        url: "https://{{ inventory_hostname }}"
        title: BIG-IP
        width: 1024
        height: 768
        screenshot: true
        screenshot_prefix: "{{ inventory_hostname }}_"
        screenshot_type: file
        screenshot_when: ['all']
        validate_cert: False
        implicit_wait: 60
        explicit_wait: 20
        steps:
          - name: Login_Username
            keys:
              type: 'find_element_by_id'
              value: 'username'
              text: '{{ f5_gui_user }}'
          - name: Login_Password
            keys:
              type: 'find_element_by_id'
              value: 'passwd'
              text: '{{ f5_gui_pass }}'
              key: 'RETURN'
            wait_for:
              method: 'invisibility_of_element_located'
              type: 'ID'
              text: 'messagetitle'
          - name: Home
            wait_for:
              method: 'presence_of_element_located'
              type: 'LINK_TEXT'
              text: 'Options'
          - name: System
            click:
              type: 'find_element_by_link_text'
              text: 'System'
            wait_for:
              method: 'presence_of_element_located'
              type: 'LINK_TEXT'
              text: 'License'
          - name: License
            click:
              type: 'find_element_by_link_text'
              text: 'License'
            wait_for:
              method: 'invisibility_of_element_located'
              type: 'ID'
              text: 'messagetitle'
          - name: Statistics
            click:
              type: 'find_element_by_link_text'
              text: 'Statistics'
            wait_for:
              method: 'presence_of_element_located'
              type: 'LINK_TEXT'
              text: 'Module Statistics'
          - name: Module_Statistics
            click:
              type: 'find_element_by_link_text'
              text: 'Module Statistics'
            wait_for:
              method: 'invisibility_of_element_located'
              type: 'ID'
              text: 'messagetitle'
          - name: Logout
            click:
              type: 'find_element_by_link_text'
              text: 'Log out'
            wait_for:
              method: 'presence_of_element_located'
              type: 'ID'
              text: 'username'
