---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Debug
      debug: var=inventory_hostname

    - name: selenium
      selenium_test:
        url: https://www.python.org
        browser: phantomjs
        title: Python
        width: 1024
        height: 768
        screenshot: true
        screenshot_prefix: python_
        screenshot_type: file
        screenshot_when: ['start', 'end', 'error', 'all']
        validate_cert: True
        steps:
          - name: Login
            keys:
              type: 'find_element_by_id'
              value: 'id-search-field'
              text: 'garbage'
              key: 'RETURN'
            wait_for:
              method: 'presence_of_element_located'
              type: 'LINK_TEXT'
              text: 'Python 2.0'
          - click:
              type: 'find_element_by_link_text'
              text: 'About'
            wait_for:
              method: 'presence_of_element_located'
              type: 'LINK_TEXT'
              text: 'Conferences and Workshops'
          - click:
              type: 'find_element_by_link_text'
              text: 'Downloads'
            wait_for:
              method: 'presence_of_element_located'
              type: 'LINK_TEXT'
              text: 'Download Python 3.5.2'
          - name: Documentation
            click:
              type: 'find_element_by_link_text'
              text: 'Documentation'
            wait_for:
              method: 'presence_of_element_located'
              type: 'LINK_TEXT'
              text: 'Python 3.x Docs'
            assert:
              - type: 'find_element_by_link_text'
                text: 'Documentation'
              - type: 'find_element_by_link_text'
                text: 'Documentation'
