---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Debug
      debug: var=inventory_hostname

    - name: selenium
      selenium:
        url: http://www.python.org
        title: Python
        width: 1024
        height: 768
        screenshot: true
        screenshot_prefix: python_
        screenshot_type: file
        screenshot_when: ['start', 'end', 'error', 'all']
        validate_cert: True
        steps:
          - step:
              click:
                type: 'find_element_by_link_text'
                text: 'About'
              wait_for:
                type: 'LINK_TEXT'
                text: 'Conferences and Workshops'
          - step:
              click:
                type: 'find_element_by_link_text'
                text: 'Downloads'
              wait_for:
                type: 'LINK_TEXT'
                text: 'Download Python 3.5.2'
          - step:
              name: Documentation
              click:
                type: 'find_element_by_link_text'
                text: 'Documentation'
              wait_for:
                type: 'LINK_TEXT'
                text: 'Python 3.x Docs'
              assert:
                - type: 'find_element_by_link_text'
                  text: 'Documentation'
                - type: 'find_element_by_link_text'
                  text: 'Documentation'
